/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Int } from "./ERC20Int";
export type { ERC20IntBurnable } from "./ERC20IntBurnable";
export type { IERC20Burnable } from "./IERC20Burnable";
export type { IERC20Int } from "./IERC20Int";
