/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUnitsPool } from "./IUnitsPool";
export type { IngotsUnitsPool } from "./IngotsUnitsPool";
export type { WorkersUnitsPool } from "./WorkersUnitsPool";
