/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IUnitsPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateTokensForExactUnits"
      | "lastPurchaseTime"
      | "relatedRegion"
      | "swapTokensForExactUnits"
      | "swapTokensForExactUnitsByRegion"
      | "unitPrice"
      | "unitTypeId"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "UnitsBought"): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateTokensForExactUnits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPurchaseTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relatedRegion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactUnits",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapTokensForExactUnitsByRegion",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unitPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unitTypeId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateTokensForExactUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPurchaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relatedRegion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapTokensForExactUnitsByRegion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unitPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unitTypeId", data: BytesLike): Result;
}

export namespace UnitsBoughtEvent {
  export type InputTuple = [
    spender: AddressLike,
    armyAddress: AddressLike,
    boughtUnitsAmount: BigNumberish,
    spentTokensAmount: BigNumberish,
    newUnitPrice: BigNumberish
  ];
  export type OutputTuple = [
    spender: string,
    armyAddress: string,
    boughtUnitsAmount: bigint,
    spentTokensAmount: bigint,
    newUnitPrice: bigint
  ];
  export interface OutputObject {
    spender: string;
    armyAddress: string;
    boughtUnitsAmount: bigint;
    spentTokensAmount: bigint;
    newUnitPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IUnitsPool extends BaseContract {
  connect(runner?: ContractRunner | null): IUnitsPool;
  waitForDeployment(): Promise<this>;

  interface: IUnitsPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateTokensForExactUnits: TypedContractMethod<
    [unitsToBuy: BigNumberish],
    [[bigint, bigint] & { tokensToSell: bigint; newUnitPrice: bigint }],
    "view"
  >;

  lastPurchaseTime: TypedContractMethod<[], [bigint], "view">;

  relatedRegion: TypedContractMethod<[], [string], "view">;

  swapTokensForExactUnits: TypedContractMethod<
    [
      tokensOwner: AddressLike,
      settlementAddress: AddressLike,
      unitsToBuy: BigNumberish,
      maxTokensToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapTokensForExactUnitsByRegion: TypedContractMethod<
    [
      tokensOwner: AddressLike,
      msgSender: AddressLike,
      settlementAddress: AddressLike,
      unitsToBuy: BigNumberish,
      maxTokensToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  unitPrice: TypedContractMethod<[], [bigint], "view">;

  unitTypeId: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateTokensForExactUnits"
  ): TypedContractMethod<
    [unitsToBuy: BigNumberish],
    [[bigint, bigint] & { tokensToSell: bigint; newUnitPrice: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastPurchaseTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relatedRegion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapTokensForExactUnits"
  ): TypedContractMethod<
    [
      tokensOwner: AddressLike,
      settlementAddress: AddressLike,
      unitsToBuy: BigNumberish,
      maxTokensToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapTokensForExactUnitsByRegion"
  ): TypedContractMethod<
    [
      tokensOwner: AddressLike,
      msgSender: AddressLike,
      settlementAddress: AddressLike,
      unitsToBuy: BigNumberish,
      maxTokensToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unitPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unitTypeId"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "UnitsBought"
  ): TypedContractEvent<
    UnitsBoughtEvent.InputTuple,
    UnitsBoughtEvent.OutputTuple,
    UnitsBoughtEvent.OutputObject
  >;

  filters: {
    "UnitsBought(address,address,uint256,uint256,uint256)": TypedContractEvent<
      UnitsBoughtEvent.InputTuple,
      UnitsBoughtEvent.OutputTuple,
      UnitsBoughtEvent.OutputObject
    >;
    UnitsBought: TypedContractEvent<
      UnitsBoughtEvent.InputTuple,
      UnitsBoughtEvent.OutputTuple,
      UnitsBoughtEvent.OutputObject
    >;
  };
}
