/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ITileCapturingSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beginTileCapture"
      | "cancelTileCapture"
      | "claimTileCapture"
      | "getCapturedTilesBySettlementAddress"
      | "giveUpCapturedTile"
      | "handleSettlementCreatedOnPosition"
      | "settlementCapturingTile"
      | "tilesInfo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapturedTileClaimed"
      | "CapturedTileGivenUp"
      | "TileCapturingBegan"
      | "TileCapturingCancelled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beginTileCapture",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTileCapture",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTileCapture",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapturedTilesBySettlementAddress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveUpCapturedTile",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleSettlementCreatedOnPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlementCapturingTile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tilesInfo",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "beginTileCapture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTileCapture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTileCapture",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapturedTilesBySettlementAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "giveUpCapturedTile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleSettlementCreatedOnPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlementCapturingTile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tilesInfo", data: BytesLike): Result;
}

export namespace CapturedTileClaimedEvent {
  export type InputTuple = [
    previousSettlementOwnerAddress: AddressLike,
    position: BigNumberish,
    settlementAddress: AddressLike,
    prosperityStake: BigNumberish
  ];
  export type OutputTuple = [
    previousSettlementOwnerAddress: string,
    position: bigint,
    settlementAddress: string,
    prosperityStake: bigint
  ];
  export interface OutputObject {
    previousSettlementOwnerAddress: string;
    position: bigint;
    settlementAddress: string;
    prosperityStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapturedTileGivenUpEvent {
  export type InputTuple = [
    position: BigNumberish,
    settlementAddress: AddressLike
  ];
  export type OutputTuple = [position: bigint, settlementAddress: string];
  export interface OutputObject {
    position: bigint;
    settlementAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TileCapturingBeganEvent {
  export type InputTuple = [
    previousUsurperAddress: AddressLike,
    position: BigNumberish,
    settlementAddress: AddressLike,
    prosperityStake: BigNumberish,
    captureBeginTime: BigNumberish,
    captureEndTime: BigNumberish
  ];
  export type OutputTuple = [
    previousUsurperAddress: string,
    position: bigint,
    settlementAddress: string,
    prosperityStake: bigint,
    captureBeginTime: bigint,
    captureEndTime: bigint
  ];
  export interface OutputObject {
    previousUsurperAddress: string;
    position: bigint;
    settlementAddress: string;
    prosperityStake: bigint;
    captureBeginTime: bigint;
    captureEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TileCapturingCancelledEvent {
  export type InputTuple = [
    position: BigNumberish,
    settlementAddress: AddressLike
  ];
  export type OutputTuple = [position: bigint, settlementAddress: string];
  export interface OutputObject {
    position: bigint;
    settlementAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITileCapturingSystem extends BaseContract {
  connect(runner?: ContractRunner | null): ITileCapturingSystem;
  waitForDeployment(): Promise<this>;

  interface: ITileCapturingSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beginTileCapture: TypedContractMethod<
    [
      settlementAddress: AddressLike,
      position: BigNumberish,
      prosperityStake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  cancelTileCapture: TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTileCapture: TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCapturedTilesBySettlementAddress: TypedContractMethod<
    [settlementAddress: AddressLike, tileBonusType: BigNumberish],
    [bigint[]],
    "view"
  >;

  giveUpCapturedTile: TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;

  handleSettlementCreatedOnPosition: TypedContractMethod<
    [position: BigNumberish],
    [void],
    "nonpayable"
  >;

  settlementCapturingTile: TypedContractMethod<
    [settlementAddress: AddressLike],
    [bigint],
    "view"
  >;

  tilesInfo: TypedContractMethod<
    [position: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        ownerSettlementAddress: string;
        usurperSettlementAddress: string;
        usurperProsperityStake: bigint;
        usurperCaptureBeginTime: bigint;
        usurperCaptureEndTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beginTileCapture"
  ): TypedContractMethod<
    [
      settlementAddress: AddressLike,
      position: BigNumberish,
      prosperityStake: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTileCapture"
  ): TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimTileCapture"
  ): TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCapturedTilesBySettlementAddress"
  ): TypedContractMethod<
    [settlementAddress: AddressLike, tileBonusType: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveUpCapturedTile"
  ): TypedContractMethod<
    [settlementAddress: AddressLike, position: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleSettlementCreatedOnPosition"
  ): TypedContractMethod<[position: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlementCapturingTile"
  ): TypedContractMethod<[settlementAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "tilesInfo"
  ): TypedContractMethod<
    [position: BigNumberish],
    [
      [string, string, bigint, bigint, bigint] & {
        ownerSettlementAddress: string;
        usurperSettlementAddress: string;
        usurperProsperityStake: bigint;
        usurperCaptureBeginTime: bigint;
        usurperCaptureEndTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CapturedTileClaimed"
  ): TypedContractEvent<
    CapturedTileClaimedEvent.InputTuple,
    CapturedTileClaimedEvent.OutputTuple,
    CapturedTileClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CapturedTileGivenUp"
  ): TypedContractEvent<
    CapturedTileGivenUpEvent.InputTuple,
    CapturedTileGivenUpEvent.OutputTuple,
    CapturedTileGivenUpEvent.OutputObject
  >;
  getEvent(
    key: "TileCapturingBegan"
  ): TypedContractEvent<
    TileCapturingBeganEvent.InputTuple,
    TileCapturingBeganEvent.OutputTuple,
    TileCapturingBeganEvent.OutputObject
  >;
  getEvent(
    key: "TileCapturingCancelled"
  ): TypedContractEvent<
    TileCapturingCancelledEvent.InputTuple,
    TileCapturingCancelledEvent.OutputTuple,
    TileCapturingCancelledEvent.OutputObject
  >;

  filters: {
    "CapturedTileClaimed(address,uint64,address,uint256)": TypedContractEvent<
      CapturedTileClaimedEvent.InputTuple,
      CapturedTileClaimedEvent.OutputTuple,
      CapturedTileClaimedEvent.OutputObject
    >;
    CapturedTileClaimed: TypedContractEvent<
      CapturedTileClaimedEvent.InputTuple,
      CapturedTileClaimedEvent.OutputTuple,
      CapturedTileClaimedEvent.OutputObject
    >;

    "CapturedTileGivenUp(uint64,address)": TypedContractEvent<
      CapturedTileGivenUpEvent.InputTuple,
      CapturedTileGivenUpEvent.OutputTuple,
      CapturedTileGivenUpEvent.OutputObject
    >;
    CapturedTileGivenUp: TypedContractEvent<
      CapturedTileGivenUpEvent.InputTuple,
      CapturedTileGivenUpEvent.OutputTuple,
      CapturedTileGivenUpEvent.OutputObject
    >;

    "TileCapturingBegan(address,uint64,address,uint256,uint64,uint64)": TypedContractEvent<
      TileCapturingBeganEvent.InputTuple,
      TileCapturingBeganEvent.OutputTuple,
      TileCapturingBeganEvent.OutputObject
    >;
    TileCapturingBegan: TypedContractEvent<
      TileCapturingBeganEvent.InputTuple,
      TileCapturingBeganEvent.OutputTuple,
      TileCapturingBeganEvent.OutputObject
    >;

    "TileCapturingCancelled(uint64,address)": TypedContractEvent<
      TileCapturingCancelledEvent.InputTuple,
      TileCapturingCancelledEvent.OutputTuple,
      TileCapturingCancelledEvent.OutputObject
    >;
    TileCapturingCancelled: TypedContractEvent<
      TileCapturingCancelledEvent.InputTuple,
      TileCapturingCancelledEvent.OutputTuple,
      TileCapturingCancelledEvent.OutputObject
    >;
  };
}
