/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSettlementMarketSol from "./ISettlementMarket.sol";
export type { iSettlementMarketSol };
import type * as settlementMarketSol from "./SettlementMarket.sol";
export type { settlementMarketSol };
