/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as army from "./army";
export type { army };
import type * as battle from "./battle";
export type { battle };
import type * as building from "./building";
export type { building };
import type * as era from "./era";
export type { era };
import type * as region from "./region";
export type { region };
import type * as settlement from "./settlement";
export type { settlement };
import type * as settlementsMarket from "./settlementsMarket";
export type { settlementsMarket };
import type * as siege from "./siege";
export type { siege };
import type * as tileCapturingSystem from "./tileCapturingSystem";
export type { tileCapturingSystem };
import type * as tokens from "./tokens";
export type { tokens };
import type * as unitsPool from "./unitsPool";
export type { unitsPool };
import type * as workersPool from "./workersPool";
export type { workersPool };
export type { IWorldAsset } from "./IWorldAsset";
export type { IWorldAssetFactory } from "./IWorldAssetFactory";
export type { IWorldAssetStorageAccessor } from "./IWorldAssetStorageAccessor";
export type { WorldAsset } from "./WorldAsset";
export type { WorldAssetFactory } from "./WorldAssetFactory";
export type { WorldAssetProxy } from "./WorldAssetProxy";
export type { WorldAssetStorageAccessorWithPush0 } from "./WorldAssetStorageAccessorWithPush0";
export type { WorldAssetStorageAccessorWithStaticContractCode } from "./WorldAssetStorageAccessorWithStaticContractCode";
export type { WorldAssetStorageAccessorWithoutPush0 } from "./WorldAssetStorageAccessorWithoutPush0";
