/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWorkers__factory } from "./IWorkers__factory";
export { Workers__factory } from "./Workers__factory";
