/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CrossErasMemory__factory } from "./CrossErasMemory__factory";
export { ICrossErasMemory__factory } from "./ICrossErasMemory__factory";
