/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CrossErasMemory } from "./CrossErasMemory";
export type { ICrossErasMemory } from "./ICrossErasMemory";
