/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as prosperity from "./prosperity";
export type { prosperity };
import type * as resources from "./resources";
export type { resources };
import type * as units from "./units";
export type { units };
import type * as workers from "./workers";
export type { workers };
