/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface ISettlementsMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buySettlement"
      | "buySettlementForFreeByMightyCreator"
      | "getNewSettlementCost"
      | "marketCreationTime"
      | "relatedRegion"
      | "updateState"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SettlementBought"): EventFragment;

  encodeFunctionData(
    functionFragment: "buySettlement",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buySettlementForFreeByMightyCreator",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewSettlementCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketCreationTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relatedRegion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateState",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "buySettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buySettlementForFreeByMightyCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewSettlementCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketCreationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relatedRegion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateState",
    data: BytesLike
  ): Result;
}

export namespace SettlementBoughtEvent {
  export type InputTuple = [
    settlementAddress: AddressLike,
    settlementCost: BigNumberish
  ];
  export type OutputTuple = [settlementAddress: string, settlementCost: bigint];
  export interface OutputObject {
    settlementAddress: string;
    settlementCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISettlementsMarket extends BaseContract {
  connect(runner?: ContractRunner | null): ISettlementsMarket;
  waitForDeployment(): Promise<this>;

  interface: ISettlementsMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buySettlement: TypedContractMethod<
    [
      position: BigNumberish,
      bannerId: BigNumberish,
      maxTokensToUse: BigNumberish
    ],
    [void],
    "payable"
  >;

  buySettlementForFreeByMightyCreator: TypedContractMethod<
    [position: BigNumberish, bannerId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getNewSettlementCost: TypedContractMethod<
    [timestamp: BigNumberish],
    [bigint],
    "view"
  >;

  marketCreationTime: TypedContractMethod<[], [bigint], "view">;

  relatedRegion: TypedContractMethod<[], [string], "view">;

  updateState: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buySettlement"
  ): TypedContractMethod<
    [
      position: BigNumberish,
      bannerId: BigNumberish,
      maxTokensToUse: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "buySettlementForFreeByMightyCreator"
  ): TypedContractMethod<
    [position: BigNumberish, bannerId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getNewSettlementCost"
  ): TypedContractMethod<[timestamp: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "marketCreationTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relatedRegion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateState"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "SettlementBought"
  ): TypedContractEvent<
    SettlementBoughtEvent.InputTuple,
    SettlementBoughtEvent.OutputTuple,
    SettlementBoughtEvent.OutputObject
  >;

  filters: {
    "SettlementBought(address,uint256)": TypedContractEvent<
      SettlementBoughtEvent.InputTuple,
      SettlementBoughtEvent.OutputTuple,
      SettlementBoughtEvent.OutputObject
    >;
    SettlementBought: TypedContractEvent<
      SettlementBoughtEvent.InputTuple,
      SettlementBoughtEvent.OutputTuple,
      SettlementBoughtEvent.OutputObject
    >;
  };
}
