/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Int__factory } from "./ERC20Int__factory";
export { ERC20IntBurnable__factory } from "./ERC20IntBurnable__factory";
export { IERC20Burnable__factory } from "./IERC20Burnable__factory";
export { IERC20Int__factory } from "./IERC20Int__factory";
