/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ProxyReentrancyGuard,
  ProxyReentrancyGuardInterface,
} from "../../../contracts/periphery/ProxyReentrancyGuard";

const _abi = [
  {
    inputs: [],
    name: "ReentrantCall",
    type: "error",
  },
] as const;

export class ProxyReentrancyGuard__factory {
  static readonly abi = _abi;
  static createInterface(): ProxyReentrancyGuardInterface {
    return new Interface(_abi) as ProxyReentrancyGuardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ProxyReentrancyGuard {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ProxyReentrancyGuard;
  }
}
