/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IResource__factory } from "./IResource__factory";
export { Resource__factory } from "./Resource__factory";
