/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IWorkersPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateProsperityForExactWorkers"
      | "lastPurchaseTime"
      | "relatedRegion"
      | "swapProsperityForExactWorkers"
      | "workerPrice"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "WorkersBought"): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateProsperityForExactWorkers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPurchaseTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relatedRegion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapProsperityForExactWorkers",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "workerPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateProsperityForExactWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPurchaseTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relatedRegion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapProsperityForExactWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workerPrice",
    data: BytesLike
  ): Result;
}

export namespace WorkersBoughtEvent {
  export type InputTuple = [
    buyerSettlementAddress: AddressLike,
    boughtWorkersAmount: BigNumberish,
    spentProsperityAmount: BigNumberish
  ];
  export type OutputTuple = [
    buyerSettlementAddress: string,
    boughtWorkersAmount: bigint,
    spentProsperityAmount: bigint
  ];
  export interface OutputObject {
    buyerSettlementAddress: string;
    boughtWorkersAmount: bigint;
    spentProsperityAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IWorkersPool extends BaseContract {
  connect(runner?: ContractRunner | null): IWorkersPool;
  waitForDeployment(): Promise<this>;

  interface: IWorkersPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateProsperityForExactWorkers: TypedContractMethod<
    [workersToBuy: BigNumberish],
    [[bigint, bigint] & { prosperityToSell: bigint; newWorkerPrice: bigint }],
    "nonpayable"
  >;

  lastPurchaseTime: TypedContractMethod<[], [bigint], "view">;

  relatedRegion: TypedContractMethod<[], [string], "view">;

  swapProsperityForExactWorkers: TypedContractMethod<
    [
      settlementAddress: AddressLike,
      workersToBuy: BigNumberish,
      maxProsperityToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  workerPrice: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateProsperityForExactWorkers"
  ): TypedContractMethod<
    [workersToBuy: BigNumberish],
    [[bigint, bigint] & { prosperityToSell: bigint; newWorkerPrice: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastPurchaseTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "relatedRegion"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapProsperityForExactWorkers"
  ): TypedContractMethod<
    [
      settlementAddress: AddressLike,
      workersToBuy: BigNumberish,
      maxProsperityToSell: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "workerPrice"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "WorkersBought"
  ): TypedContractEvent<
    WorkersBoughtEvent.InputTuple,
    WorkersBoughtEvent.OutputTuple,
    WorkersBoughtEvent.OutputObject
  >;

  filters: {
    "WorkersBought(address,uint256,uint256)": TypedContractEvent<
      WorkersBoughtEvent.InputTuple,
      WorkersBoughtEvent.OutputTuple,
      WorkersBoughtEvent.OutputObject
    >;
    WorkersBought: TypedContractEvent<
      WorkersBoughtEvent.InputTuple,
      WorkersBoughtEvent.OutputTuple,
      WorkersBoughtEvent.OutputObject
    >;
  };
}
