/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWorldInitializable,
  IWorldInitializableInterface,
} from "../../../contracts/core/IWorldInitializable";

const _abi = [
  {
    inputs: [],
    name: "OnlyActiveGame",
    type: "error",
  },
  {
    inputs: [],
    name: "world",
    outputs: [
      {
        internalType: "contract IWorld",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWorldInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): IWorldInitializableInterface {
    return new Interface(_abi) as IWorldInitializableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWorldInitializable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWorldInitializable;
  }
}
