/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  WorldInitializable,
  WorldInitializableInterface,
} from "../../../contracts/core/WorldInitializable";

const _abi = [
  {
    inputs: [],
    name: "OnlyActiveGame",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "world",
    outputs: [
      {
        internalType: "contract IWorld",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class WorldInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): WorldInitializableInterface {
    return new Interface(_abi) as WorldInitializableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): WorldInitializable {
    return new Contract(address, _abi, runner) as unknown as WorldInitializable;
  }
}
